### ISSUE TITLE
Anonymous participant displaying its status, FPS, latency, etc.

### ISSUE THREAD

**Issue by luisnavarrodelangel** [dktr0/estuary#112]
When an anonymous participant enters the ensemble, the ensembleStatusWidget displays its text input, FPS, latency, etc. This is located in the file Estuary/Widgets/EnsembleStatus.hs

**Comment by dktr0** [comment]
Fixed via https://github.com/dktr0/estuary/commit/11345515927ba06ab37060249d2c115085b65f88
