### ISSUE TITLE
client should block browser back behaviour (but in a non-annoying way)

### ISSUE THREAD

**Issue by dktr0** [dktr0/estuary#13]
It is very annoying (to say the least) to accidentally activate the browser's back functionality while in the middle of a performance!

**Comment by d0kt0r0** [comment]
A recent commit at least has it that a pop up comes and asks you if you really want to go back / close the page / etc. However and unfortunately, audio output still stops while this dialog displays so this does not really cover the requirements for something that will be robust in "performance" situations.

**Comment by d0kt0r0** [comment]
We should put in some hacky things to catch typical user mistakes that go back such as pressing backspace when not focused on a text area, or certain swipe gestures.

**Comment by SpencerPark** [comment]
We do have the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) which estuary could make use of. Conventionally this would be used to connect the browser navigation buttons to a single page app but we can do the opposite.

Its a bit frustrating when other sites do this but I believe we can populate the history when the user navigates to a view that produces sound (like an ensemble) such that hitting back actually just changes the hash so we can detect it but not causing a reload (or interruption of audio). We would then ensure that our embedded back button actually goes around the little hack we put in place.

The only danger with this is that users who are unaware that this is supposed to be helpful may find it the opposite extreme. I think something like requiring back to be hit twice (like a confirmation) within 2 sec or similar and a notification appearing somewhere in the app explaining this could suffice.
