### ISSUE TITLE
should be a visible warning when modifying an ensemble without password

### ISSUE THREAD

**Issue by dktr0** [dktr0/estuary#17]
because that mistake is very easy to make and sometimes hard to realize that you have made it.

**Comment by d0kt0r0** [comment]
After a discussion at a meeting, we are moving towards a system where joining an ensemble requires both a modal entry of a name/handle, and a modal entry of a password (with interactive confirmation that the password is correct/incorrect and the option to proceed without a correct password).

**Comment by dktr0** [comment]
Resolved by recent refactor (if you enter a password of any kind it must be correct - or else you don't enter the ensemble - you can still enter without the password (without the ability to transmit edits)).
