### ISSUE TITLE
Minitidal: stutWith is broken

### ISSUE THREAD

**Issue by cleary** [dktr0/estuary#183]
Hi David, 

I was just trying to do some testing with `stutWith`, but I could not get it going in estuary. This works fine in tidal (proper):

```
stutWith 4 0.1 (* gain 0.8)
$ s "bd"
```
but throws the following error in estuary:
> 1:1 expected ControlPattern

**Comment by dktr0** [comment]
Looks like stutWith isn't in tidal-parse yet. Will put it on the to-do list!

**Comment by dktr0** [comment]
stutWith is now available.
