### ISSUE TITLE
docker builds

### ISSUE THREAD

**Issue by bytosaur** [dktr0/estuary#193]
hey there,

i just saw a couple of live coders using your tool on an event called on-the-fly which took place at ZKM Karlsruhe. I really dig the tool although I am pretty new to the live coding community. Unfortunately, the ping was sometimes pretty high.

Do you have any images for docker ? This would facilitate the process of deploying other instances so much :)

**Comment by dktr0** [comment]
We don't, and I'm afraid it is not something I have the time nor interest in working on.

Tangentially, I will mention that there are many things than can influence the round trip ping time - I have seen very good performance for some European clients. Additionally, the measurement of round trip time seen in the web client can be misleading - for example, in circumstances when the browser is experiencing significant processing load, the figures are basically useless/meaningless. This can *sometimes* lead people to believe there is a long latency in communication with the server, when in fact it is the far more common issue of the browser being asked to process too much stuff. Your mileage may vary of course...

Thanks for your interest!

**Comment by bytosaur** [comment]
Hey there,

Thanks a lot for the very detailed description of how the latency is calculated and I have to admit that by no means I took a reliable measurement.
I ll let you know if I manage to get a basic docker image when I find some time.

Keep it up :)
