### ISSUE TITLE
Togo underscore notation giving same results as x notation

### ISSUE THREAD

**Issue by dktr0** [dktr0/estuary#59]
eg. 3x8 is the same as 3_8. cause is that _euclidInv is erroneously defined the same way as _euclid in Togo.hs.

**Comment by d0kt0r0** [comment]
I believe Tidal has adopted the more efficient definitions here (but presumably with the correct ones for the inverse Euclid pattern!) so we can probably just delete the euclid implementations here, upgrade to a more recent Tidal, and use the implementations from Tidal again.

**Comment by dktr0** [comment]
Resolved.
