### ISSUE TITLE
No sounds coming out

### ISSUE THREAD

**Issue by RanggaPAji** [dktr0/estuary#82]
Hi, this is my first time with Estuary and i tried to eval a simple code like `d1 $ s "bd"` in Estuary solo mode but no sound coming out. I tried to check the tutorial, thinking that maybe i need to install something. But i only found the MiniTidal tutorial. So should i install something first before i use the Estuary? thanks.

**Comment by dktr0** [comment]
Don't put d1 $ at the front - just s "bd" - and it will work.
