### ISSUE TITLE
Cannot create a "new ensemble"

### ISSUE THREAD

**Issue by RanggaPAji** [dktr0/estuary#83]
Hi, I just tried to make a new ensemble for live coding with my friend from Argentina. But, whenever me or my friend couldn't create a new ensemble. The name doesn't pop-out on the list.

**Comment by dktr0** [comment]
Do you see the name of other ensembles in the list? Or no names at all?

**Comment by dktr0** [comment]
If you see other names, it's probably you just don't have the right administrator password. Right now that password is "morelia". Let us know if this resolves the issue or not - thanks!

**Comment by RanggaPAji** [comment]
Hi!, yes it worked now. Our friend from Algorave India told us the administrator password. We made the CLiC Ensemble on the Estuary. Thanks so much!

**Comment by dktr0** [comment]
Awesome - welcome aboard! There is also the #estuary channel on toplap.lurk.org and the google email list estuary as another place for chatting/help/etc about Estuary https://groups.google.com/forum/#!forum/estuary, by the way.

**Comment by RanggaPAji** [comment]
Thanks man! i'll check those out ASAP. cheers!
